package policies

type Policy struct {
	Name                   string   `json:"name"`
	Description            string   `json:"description"`
	Enabled                bool     `json:"enabled"`
	Scope                  *string  `json:"scope"`
	RuleNames              []string `json:"ruleNames"`
	NotificationChannelIds []string `json:"notificationChannelIds"`
	Severity               int      `json:"severity"`
	Actions                []string `json:"actions"`
	Type                   string   `json:"type"`
}

var SysdigRuntimeThreatIntelligence = Policy{
	Name:        "Sysdig Runtime Threat Intelligence",
	Description: "This policy contains rules using Indicators of Compromise curated by the Sysdig Threat Intelligence Team from premium, OSINT, and custom threat intelligence feeds. Any events from the rules in this policy should be considered serious and investigated as soon as possible.",
	Enabled:     true,
	Scope:       nil,
	RuleNames: []string{
		"Ransomware Filenames Detected",
		"Detect crypto miners using the Stratum protocol",
		"Detect outbound connections to TOR Entry Nodes",
		"Detect outbound connections to common miner pool ports",
		"Launch malicious container image",
		"Malicious IPs or domains detected on command line",
		"Malicious binary detected",
		"Malicious Environment Variable in Spawned Process",
		"Malicious filenames written",
		"Outbound Connection to C2 Servers",
		"Connection to IPFS Network Detected",
		"Kill known malicious process",
		"Detect outbound connections to Proxy/VPN",
	},
	NotificationChannelIds: []string{},
	Severity:               0,
	Actions:                []string{},
	Type:                   "falco",
}

var SysdigRuntimeThreatDetection = Policy{
	Name:        "Sysdig Runtime Threat Detection",
	Description: "This policy contains rules which Sysdig considers High Confidence of a security incident. They are tightly coupled to common attacker TTP's. They have been designed to minimize false positives but may still result in some depending on your environment.",
	Enabled:     true,
	Scope:       nil,
	RuleNames: []string{
		"Change memory swap options",
		"Create Hardlink Over Sensitive Files",
		"Packet socket created in container",
		"Base64'd ELF file on Command Line",
		"Base64-encoded Python Script Execution",
		"Base64-encoded Shell Script Execution",
		"Create Symlink Over Sensitive Files",
		"Debugfs Launched in Privileged Container",
		"Detect curl Using Socks Proxy",
		"eBPF Program Loaded into Kernel",
		"Execution from /dev/shm",
		"Find AWS Credentials",
		"Modify ld.so.preload",
		"Mount Launched in Privileged Container",
		"Netcat Remote Code Execution in Container",
		"Polkit Local Privilege Escalation Vulnerability (CVE-2021-4034)",
		"Possible Backdoor using BPF",
		"Reconnaissance attempt to find SUID binaries",
		"Search Private Keys or Passwords",
		"Sudo Potential Privilege Escalation",
		"Suspicious Home Directory Creation",
		"Tampering with Security Software in Container",
		"Detect malicious cmdlines",
		"Detect reconnaissance scripts",
		"PTRACE anti-debug attempt",
		"PTRACE attached to process",
		"GPG Key Reconnaissance",
		"Dump memory for credentials",
		"Diamorphine Rootkit Activity",
		"Unexpected Connection from legitimate Process/Port",
		"Contact EC2 Instance Metadata Service From Container",
		"Detect cloned process by PRoot",
		"Debugfs Launched on Host",
		"Suspicious OpenSSL Shared Object Loaded",
		"Hexadecimal string detected",
		"Kernel startup modules changed",
		"Find Azure Credentials",
		"Find GCP Credentials",
		"Modification of pam.d detected",
		"Contact Task Metadata Endpoint",
		"nsenter Container Escape",
		"Hide Process with Mount",
		"Abuse Sudo for Privilege Escalation",
		"Hardware Added to the System",
		"Suspicious RC Script Modification",
		"Modify Grub Configuration Files",
		"Mount on Container Path Detected",
	},
	NotificationChannelIds: []string{},
	Severity:               0,
	Actions:                []string{},
	Type:                   "falco",
}

var SysdigRuntimeNotableEvents = Policy{
	Name:        "Sysdig Runtime Notable Events",
	Description: "This Notable Events policy contains rules which may indicate undesired behavior including security threats. The rules are more generalized than Threat Detection policies and may result in more noise. Tuning will likely be required for the events generated from this policy.",
	Enabled:     true,
	Scope:       nil,
	RuleNames: []string{
		"Shutdown or Reboot detected",
		"Shell binaries opening connections",
		"Lastlog Files Cleared",
		"Clear Log Activities",
		"Create Hidden Files or Directories",
		"Create files below dev",
		"DB program spawned process",
		"Delete Bash History",
		"Delete or rename shell history",
		"Execution from /tmp",
		"Launch Package Management Process in Container",
		"Launch Privileged Container",
		"Launch Remote File Copy Tools in Container",
		"Launch Root User Container",
		"Launch Sensitive Mount Container",
		"Launch Suspicious Network Tool in Container",
		"Launch Suspicious Network Tool on Host",
		"Mkdir binary dirs",
		"Modify binary dirs",
		"Program run with disallowed http proxy env",
		"Read sensitive file untrusted",
		"Redirect STDOUT/STDIN to Network Connection in Container",
		"Remove Bulk Data from Disk",
		"Run shell untrusted",
		"Suspicious Operations with Firewalls",
		"Suspicious System Service Modification",
		"System user interactive",
		"Terminal shell in container",
		"The docker client is executed in a container",
		"Unexpected K8s NodePort Connection",
		"Suspicious Kernel Parameter Modification",
		"Suspicious Domain Contacted",
		"Execution of binary using ld-linux",
		"Redirect STDOUT/STDIN to Network Connection in Host",
		"Suspicious Java Child Processes",
		"Privileged Shell Spawned Inside Container",
		"OpenSSL File Read or Write",
		"Modify Timestamp attribute in File",
		"Disallowed SSH Connection Non Standard Port",
		"Contact GCP Instance Metadata Service from Container",
		"Contact Azure Instance Metadata Service from Container",
		"Potential IRC connection detected",
		"SSH keys added to authorized_keys",
		"AWS CLI used with endpoint url parameter",
		"Password Policy Discovery Activity Detected",
		"Service Discovery Activity Detected",
		"Suspicious Access To Kerberos Secrets",
		"Query to Window Management System Detected",
		"Suspicious Connection to K8S API Server From Container",
		"Suspicious device created in container",
		"Exfiltrating Artifacts via Kubernetes Control Plane",
		"System Geolocation Discovery",
		"Linux Kernel Module Injection Detected",
		"Suspicious Cron Modification",
		"Possible SSH Hijacking Attempt Detected",
		"Suspicious Docker Options",
		"Execution from Temporary Filesystem (tmpfs)",
		"Contact EC2 Instance Metadata Service From Host",
		"Data Split Activity Detected",
	},
	NotificationChannelIds: []string{},
	Severity:               4,
	Actions:                []string{},
	Type:                   "falco",
}

var SysdigRuntimeActivityLogs = Policy{
	Name:        "Sysdig Runtime Activity Logs",
	Description: "This policy contains rules which provide a greater insight into general activities occuring on the system. They are very noisy, but useful in threat hunting situations if you are looking for specific actions being taken during runtime. It is not recommended to use this policy for detection purposes unless tuning is enabled. Additional manual tuning will likely be required.",
	Enabled:     false,
	Scope:       nil,
	RuleNames: []string{
		"Container image built on host",
		"Change thread namespace",
		"Launch Ingress Remote File Copy Tools in Container",
		"Modify Shell Configuration File",
		"Network Connection outside Local Subnet",
		"Non sudo setuid",
		"Read Shell Configuration File",
		"Read sensitive file trusted after startup",
		"Read ssh information",
		"Schedule Cron Jobs",
		"Set Setuid or Setgid bit",
		"System procs network activity",
		"Update Package Repository",
		"User mgmt binaries",
		"Write below binary dir",
		"Write below etc",
		"Write below monitored dir",
		"Write below root",
		"Write below rpm database",
		"Users Group Management Event Detected",
		"User Management Event Detected",
		"Launch Code Compiler Tool in Container",
		"AWS SSM Agent Activity",
		"AWS SSM Agent File Write",
		"EC2 Instance Connect System Access",
		"Auditd Logging Commands",
		"Contact K8S API Server From Container",
		"Access to Clipboard Data Detected",
		"Interactive Reconnaissance Activity Detected",
		"Peripheral Device Discovery Activity Detected",
		"Contact GCP Instance Metadata Service from Host",
		"Contact Azure Instance Metadata Service from Host",
		"Find Authentication Certificates",
	},
	NotificationChannelIds: []string{},
	Severity:               7,
	Actions:                []string{},
	Type:                   "falco",
}
